### ISSUE TITLE
Missing translation, layout issue and suggestions

### ISSUE THREAD

**Issue by ghorbey** [pedrobaringo/outgunned-csb-en#1]
Hi,

Here are a few issues:

- Notas is not translated in English.
- Weapon ranges (medium mainly) are too large, you should change Medium to Med or reduce font size.
- Making a dice roll automatically use matching attribute. Having to use SHIFT+attributes is not really user friendly, I'd suggest either that the dialog is the default behavior or add an icon (with dice) before each attribute opening the dialog and pre-selecting the matching attribute.
- Using the spotlight throw the coin but getting head (or tail, I didn't checked) doesn't remove the spotlight automatically (which would be a QoL improvement)

Otherwise, it's really nice. ;-)

Ghor

**Comment by ghorbey** [comment]
I'ver added a few suggestions, thanks for your quick answer. ;-)

**Comment by pedrobaringo** [comment]
Just updated with most of your changes (I'm still thinking about the dice rolls with the dialog, I'll ask some of my players to see what they find more useful, but I like your idea).
Also when you roll the Death Roulette a bullet is added if you roll higher.
Hope you like it :-)

**Comment by ghorbey** [comment]
Great, thank you very much, that was fast. ;-)

I'll test that asap.
