### ISSUE TITLE
Lethal bullet doesn't seems to be added when you roll death roulette and don't die.

### ISSUE THREAD

**Issue by ghorbey** [pedrobaringo/outgunned-csb-en#2]
"When you use the Death Roulette and you don't die, a new Lethal bullet gets added to the roulette."

It doesn't seems to work. I've created a new character (just in case template wasn't applied)

There's an error in the console when I roll death roulette : 
https://i.imgur.com/8iyAE5T.png

Hope this helps.

**Comment by ghorbey** [comment]
Same for the spotlight, with a different error:
https://i.imgur.com/lkB9l0O.png

**Comment by pedrobaringo** [comment]
It works on my computer... What Foundry version are you using? Have you imported the Compendiums? Can you try adding the Bullet manually and try again?

**Comment by ghorbey** [comment]
Ok, I've got to delete the templates and now it works. Forget about this issue. (But the import option in chat dialog doesn't seems to replace and keep id)

**Comment by pedrobaringo** [comment]
It's strange, for me the Import in the chat worked replacing the templates and keeping the Ids. Let me know if you find any more issues. Thanks a lot!
