### ISSUE TITLE
Issues with 1.0.3

### ISSUE THREAD

**Issue by darune123** [pedrobaringo/outgunned-csb-en#3]
Updated to latest version. Now players do not have permission to roll dice due to error: You do not have permission to execute macro Roll Reroll All In

What do I need to do fix this?

Additionally the formatting on the feats cause the title background to extend over the text area.

I am using the english version

**Comment by pedrobaringo** [comment]
For the first problem, you need to give permissions to the players for the Macro.
For the second issue I would need a screen capture, but maybe it's because you need to update the CSB system to the latest version or you need to refresh the sheets.
Let me know if it solves the problem.

**Comment by darune123** [comment]
All the players have permission for the Macros. I am using the latest CSB. As the GM I have no issue rolling from a sheet, but as a player, we are getting the error.

I did refresh the sheet, and it did fix the css issue on the page with the feats (on The Forge vtt, but on Foundry I can't get the css cleared). 
In one of the images I have the CSB version.

Let me know if there is anything else I can do. Thanks.

![macro-configure](https://github.com/pedrobaringo/outgunned-csb-en/assets/120995995/7bfc38ca-7340-40e8-af69-278414a7b895)
![permissions](https://github.com/pedrobaringo/outgunned-csb-en/assets/120995995/4dda181b-0ef3-4eab-8d77-e41fcee41322)

**Comment by pedrobaringo** [comment]
You have to give them ownership of the Macro. At least Oberver. You can find the macro in the macro folder on the bottom of the screen.
![image](https://github.com/pedrobaringo/outgunned-csb-en/assets/148097688/bb96c1d8-6b27-4af7-b740-97ab2a3c8910)
![image](https://github.com/pedrobaringo/outgunned-csb-en/assets/148097688/162e3cbc-b8cb-400d-bc71-b41897cfd806)
![image](https://github.com/pedrobaringo/outgunned-csb-en/assets/148097688/bd4d38ce-3ed1-4be9-b591-55ec2d2ccf0d)

I don't know why the CSS doesn't work on Foundry but it does on Forge, I don't have Forge and it works for me.

**Comment by darune123** [comment]
That worked... Thanks. Now back to having fun! I like the updates. The portrait version of the characters is great - easy to use. Thanks
Now to figure out how how to change the Outgunned dice to different colors.
